name: delivery_app
description: Sistema de delivery con mÃºltiples roles (Admin, Repartidor, Cliente)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  firebase_database: ^10.4.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10

  # Security
  crypto: ^3.0.3

  # State Management
  provider: ^6.1.1

  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

  # Maps and Location
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  geocoding: ^2.1.1

  # Utilities
  image_picker: ^1.0.5
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  http: ^1.1.2
  uuid: ^4.2.2
  url_launcher: ^6.3.2

  # Sensors
  sensors_plus: ^4.0.2
  flutter_local_notifications: ^20.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/branding/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/branding/delivery.jpg
  remove_alpha_ios: true

flutter_native_splash:
  color: "#000000"
  image: assets/branding/delivery.jpg
  android: true
  ios: true
  android_12:
    color: "#000000"
    image: assets/branding/delivery.jpg
